apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  sources:
    # 1️⃣ Helm chart source from Grafana Helm repo
    - repoURL: https://grafana.github.io/helm-charts
      chart: loki-stack
      targetRevision: 2.10.2
      helm:
        valueFiles:
          - $values/Monitoring/loki-values.yaml

    # 2️⃣ Git repo source containing your loki-values.yaml
    - repoURL: 'https://github.com/maheshgowdamg/Argocd-deploy.git'
      targetRevision: HEAD
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  
